<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
    'enabled' => array(
        'title' => __('Enable/Disable', 'woocommerce'),
        'type' => 'checkbox',
        'label' => __('Enable TapTree Payments', 'woocommerce'),
        'default' => 'no'
    ),
    'api_key_test' => array(
        'title' => __('Test API Key', 'woocommerce'),
        'type' => 'api_key',
        'input_type' => 'password',
        'description' => __('Insert your TapTree API test key here. Don\'t have an API key yet? Get one in your TapTree dashboard. Attention: Only use test keys here!', 'woocommerce'),
    ),
    'api_key_live' => array(
        'title' => __('Live API Key', 'woocommerce'),
        'type' => 'api_key',
        'input_type' => 'password',
        'description' => __('Attention: This key is used to process payments in live mode!', 'woocommerce'),
    ),
    'live_mode' => array(
        'title' => __('Live Mode', 'woocommerce'),
        'type' => 'checkbox',
        'label' => __('Live mode', 'woocommerce'),
        'description' => __( 'Check this option for live mode. Attention: Payments are only processed if this option is checked and a valid TapTree API live key is provided. Uncheck the option for testing, free of charge.', 'woocommerce' ),
        'default' => 'no'
    ),
    'alt_title' => array(
        'title' => __('Title', 'woocommerce'),
        'type' => 'checkbox',
        'label' => __('Set title of payment method to "TapTree Payments"', 'woocommerce'),
        'description' => __( 'Check this option if you want to set the title of the payment method to "TapTree Payments" instead of "Kreditkarte und mehr"', 'woocommerce' ),
        'default' => 'no',
        'desc_tip'      => true,
    ),
    'as_redirect' => array(
        'title' => __('Popup', 'woocommerce'),
        'type' => 'checkbox',
        'label' => __('Checkout as redirect', 'woocommerce'),
        'description' => __( 'Check this option if you do not want to open the TapTree Checkout Popup but have your clients redirected instead.', 'woocommerce' ),
        'default' => 'no',
        'desc_tip'      => true,
    ),
    'show_impact' => array(
        'title' => __('Show Impact', 'woocommerce'),
        'type' => 'checkbox',
        'label' => __('Display the Impact of payments in checkout an on thank you page', 'woocommerce'),
        'description' => __( 'Check this option if you want to display the Impact generated by your payments in the checkout and on the thank you page.', 'woocommerce' ),
        'default' => 'yes',
        'desc_tip'      => true,
    ),
    'payment_method_logos' => array(
        'title' => __('Payment Method Logos', 'woocommerce'),
        'type' => 'payment_method_logos',
        'label' => __('', 'woocommerce'),
        'description' => __('Configure which payment method logos will be displayed on the checkout page. Only the methods available for your current api key settings are displayed here. If the payment methods available change for any reason (e.g. different api key settings or toggling the "Enabled" state) all available methods will be checked by default.', 'woocommerce'),
    ),
);
