name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy Release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code (necessary for GitHub Actions to fetch context)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Subversion
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      # Step 3: Download the release zip from GitHub
      - name: Download release zip
        run: |
          LATEST_TAG=$(echo "${GITHUB_REF}" | sed 's|refs/tags/||')
          RELEASE_URL="https://github.com/taptreepay/taptree-woocommerce/releases/download/$LATEST_TAG/taptree-payments-for-woocommerce-$LATEST_TAG.zip"
          echo "Downloading release from: $RELEASE_URL"
          curl -L -o release.zip "$RELEASE_URL"

      # Step 4: Extract the zip
      - name: Extract release zip
        run: unzip -q release.zip -d plugin

      # Step 5: Deploy to WordPress.org
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: taptree-payments-for-woocommerce
