name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      # Install dependencies
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion
      - name: Install Composer
        run: |
          sudo apt-get install -y curl php php-curl
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          sudo composer self-update
          composer -v

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the project
      - name: Build project
        run: |
          npm install
          npm run build
          composer install --no-dev --prefer-dist

      # Deploy everything we've just built to WordPress.org
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: taptree-payments-for-woocommerce
